const path = require("path");
const dotenv = require("dotenv");
const express = require("express");
const bcrypt = require("bcrypt");
const jwt = require("jsonwebtoken");
const { Pool } = require("pg");

dotenv.config({ path: path.join(__dirname, ".env.local"), quiet: true });
dotenv.config({ path: path.join(__dirname, ".env"), quiet: true });

const app = express();

const JWT_SECRET = process.env.JWT_SECRET || "my-super-secret-key";
const DATABASE_URL = process.env.DATABASE_URL;

if (!DATABASE_URL) {
    console.error("DATABASE_URL is not set. Run `neon link` or add it to your .env file.");
    process.exit(1);
}

function createPoolConfig(connectionString) {
    const databaseUrl = new URL(connectionString);
    const sslMode = databaseUrl.searchParams.get("sslmode");

    if (!sslMode) {
        return { connectionString };
    }

    databaseUrl.searchParams.delete("sslmode");

    if (sslMode === "disable") {
        return {
            connectionString: databaseUrl.toString(),
            ssl: false
        };
    }

    return {
        connectionString: databaseUrl.toString(),
        ssl: {
            rejectUnauthorized: sslMode !== "no-verify"
        }
    };
}

const db = new Pool(createPoolConfig(DATABASE_URL));

app.use(express.json());
app.use(express.static(path.join(__dirname, "public")));

async function initializeDatabase() {
    await db.query(`
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            email TEXT UNIQUE NOT NULL,
            password TEXT NOT NULL
        )
    `);

    await db.query(`
        CREATE TABLE IF NOT EXISTS todos (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            task TEXT NOT NULL,
            done INTEGER NOT NULL DEFAULT 0 CHECK (done IN (0, 1)),
            user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE
        )
    `);
}

// SIGNUP
app.post("/signup", async (req, res, next) => {

    const { name, email, password } = req.body;

    if (!name || !email || !password) {
        return res.status(400).json({
            message: "All fields are required."
        });
    }

    try {
        const existingUser = await db.query(`
            SELECT id FROM users
            WHERE email = $1
        `, [email]);

        if (existingUser.rowCount > 0) {
            return res.status(400).json({
                message: "Email already registered."
            });
        }

        const hashedPassword = await bcrypt.hash(password, 10);

        await db.query(`
            INSERT INTO users (name, email, password)
            VALUES ($1, $2, $3)
        `, [name, email, hashedPassword]);

        res.json({
            message: "Account created successfully."
        });
    } catch (error) {
        if (error.code === "23505") {
            return res.status(400).json({
                message: "Email already registered."
            });
        }

        next(error);
    }
});


// LOGIN
app.post("/login", async (req, res, next) => {

    const { email, password } = req.body;

    try {
        const result = await db.query(`
            SELECT * FROM users
            WHERE email = $1
        `, [email]);

        const user = result.rows[0];

        if (!user) {
            return res.status(401).json({
                message: "Invalid email or password."
            });
        }

        const passwordMatches =
            await bcrypt.compare(password, user.password);

        if (!passwordMatches) {
            return res.status(401).json({
                message: "Invalid email or password."
            });
        }

        const token = jwt.sign(
            {
                userId: user.id,
                name: user.name
            },
            JWT_SECRET,
            {
                expiresIn: "2h"
            }
        );

        res.json({
            token: token,
            name: user.name
        });
    } catch (error) {
        next(error);
    }
});


// AUTH MIDDLEWARE
function authenticate(req, res, next) {

    const authHeader = req.headers.authorization;

    if (!authHeader) {
        return res.status(401).json({
            message: "No token provided."
        });
    }

    const token = authHeader.split(" ")[1];

    try {

        const user = jwt.verify(
            token,
            JWT_SECRET
        );

        req.user = user;

        next();

    } catch (error) {

        return res.status(401).json({
            message: "Invalid or expired token."
        });

    }
}


// GET TODOS FOR LOGGED-IN USER
app.get("/todos", authenticate, async (req, res, next) => {

    try {
        const result = await db.query(`
            SELECT id, task, done, user_id
            FROM todos
            WHERE user_id = $1
            ORDER BY id
        `, [req.user.userId]);

        res.json(result.rows);
    } catch (error) {
        next(error);
    }
});


// CREATE TODO FOR LOGGED-IN USER
app.post("/todos", authenticate, async (req, res, next) => {

    const task = req.body.task;

    try {
        await db.query(`
            INSERT INTO todos (task, user_id)
            VALUES ($1, $2)
        `, [task, req.user.userId]);

        res.json({
            message: "Todo added."
        });
    } catch (error) {
        next(error);
    }
});


// COMPLETE TODO
app.patch("/todos/:id", authenticate, async (req, res, next) => {

    const id = req.params.id;

    try {
        await db.query(`
            UPDATE todos
            SET done = 1
            WHERE id = $1
            AND user_id = $2
        `, [id, req.user.userId]);

        res.json({
            message: "Todo completed."
        });
    } catch (error) {
        next(error);
    }
});


// DELETE TODO
app.delete("/todos/:id", authenticate, async (req, res, next) => {

    const id = req.params.id;

    try {
        await db.query(`
            DELETE FROM todos
            WHERE id = $1
            AND user_id = $2
        `, [id, req.user.userId]);

        res.json({
            message: "Todo deleted."
        });
    } catch (error) {
        next(error);
    }
});

app.get("/login-page", authenticate, (req, res) => {
    res.sendFile(
        path.join(__dirname, "public", "login.html")
    );
}); 

app.use((error, req, res, next) => {
    console.error(error);

    res.status(500).json({
        message: "Server error."
    });
});

// Remove the app.listen() code and replace with:

// For Vercel serverless
if (process.env.VERCEL) {
  module.exports = app;
} else {
  // For local development
  const PORT = process.env.PORT || 3000;
  
  initializeDatabase().then(() => {
    app.listen(PORT, () => {
      console.log(`Server running on http://localhost:${PORT}`);
    });
  }).catch((error) => {
    console.error("Failed to initialize database:", error);
    process.exit(1);
  });
}

// Initialize DB on Vercel
if (process.env.VERCEL) {
  initializeDatabase().catch((error) => {
    console.error("Failed to initialize database:", error);
  });
}
